### ISSUE TITLE
possible error while installing

### ISSUE THREAD

**Issue by sanjmeh** [msberends/clean#1]
`Note: possible error in 'trimws(x, which = "both", ': unused argument (whitespace = "[ \t\r\n]") `

While installing the package from CRAN and even from source (devtools) it gives above error. Seems a trivial error but nevertheless bringing to your notice.

**Comment by msberends** [comment]
Thanks! I was shocked to learn this today. Came to my attention by the CRAN checks: https://cran.r-project.org/web/checks/check_results_clean.html

Apparently, it’s a macOS error when using R versions 3.5 or lower. Updating your R version to 3.6 or later should fix it, but I will also fix it for users working with older R versions. 

Sorry for the inconvenience and thank you very much for letting me know.

**Comment by msberends** [comment]
I can confirm that this sometimes happens on R 3.5 and lower, also on other OSes than macOS. 

I’m working on a fix. As said, updating R to at least 3.6 works too.

**Comment by sanjmeh** [comment]
I am conscious of the risks in upgrading to 3.6. Surely I do not want to land up in this mess here (https://community.rstudio.com/t/every-libraries-failed-to-load-after-upgrading-r-to-3-6-0/29736).
Before R 3.5 the upgrades were simple. But ever since 3.5 the packages have to be reinstalled and now in 3.6 it looks to have gone worse. SOmeone from the R community has to look into this as we are losing the key advantage over python if the installation process is made so complicated.

**Comment by msberends** [comment]
>  as we are losing the key advantage over python

I don’t think we’re at war with Python, now are we? These are two completely different languages with different audiences, and the one does not exclude the other, as I see it.

I’m on macOS too, and never got an issue with updating. Could also be `Rcpp` specific and a user specific problem. Of course I can’t force you to update R, and this package should work on earlier versions as well. But then you have to wait until I’ve fixed it, and CRAN accepts another update 😊
